rag:
  embedder:  dunzhang/stella_en_400M_v5 #sentence-transformers/all-MiniLM-L6-v2 #colbert-ir/colbertv2.0

openai:
  model_name: gpt-4o-mini
  temperature: 0
  max_tokens: 4096
  stream: True
  system_prompt: You are a helpful assistant.

system_prompt: You are a helpful assistant.
